version: '2.0'
services:
  db:
    image: mongo:3.5
    ports:
      - "27017:27017"
  web:
    links:
      - db
    build: .
    command: bash -c "pip3 install -r requirements.txt && python3 ./app.py"
    volumes:
      - .:/code
    ports:
      - "5000:5000"